name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Clone code-star
        run: |
          git clone https://github.com/youzarsiph/code-star
          git clone https://github.com/youzarsiph/code-star-demo
          mv code-star code_star
          mv code-star-demo code_star_demo
          
      - name: Install Dependencies
        run: |
          cp code_star/requirements.txt requirements.txt
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create a Django project and configure settings
        run: |
          python -m django startproject mysite
          cp -r code_star mysite/code_star
          cp -r code_star_demo mysite/code_star_demo
          cd mysite
          echo "INSTALLED_APPS = ['code_star', 'code_star.chats', 'code_star.completions', 'code_star_demo', 'code_star_demo.chat', 'code_star_demo.completion', 'daphne', 'channels', 'rest_framework', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.staticfiles']" >> mysite/settings.py

      - name: Configure URLConf and Routing
        run: |
          cd mysite
          echo "from django.urls import path, include" > mysite/urls.py
          echo "urlpatterns = [path('', include('code_star.urls')), path('demo/', include('code_star_demo.urls'))]" >> mysite/urls.py
          echo "from code_star.routing import app" >> mysite/asgi.py
          echo "application = app(application)" >> mysite/asgi.py

      - name: Run Migrations, System checks and test
        run: |
          cd mysite
          python manage.py migrate
          python manage.py check
          python manage.py test
